### ISSUE TITLE
ExonAndIntron GTF

### ISSUE THREAD

**Issue by singlecellfan** [vincenthahaut/FLASH-Seq#1]
Hello,

thanks for the great documentation you have provided. I am trying to analyse some Flash-seq data we generated. 
In the paired_end_umi.sh you indicate this file "gencode.v34.exonsANDintrons.gtf". I am having problems finding it on the gencode webpage. Where did you get that from? Or did you assemble it yourself?

Thanks and best regards!

**Comment by vincenthahaut** [comment]
Hi, 

This is a reference I generated using this code: https://github.com/vincenthahaut/FLASH-Seq/blob/main/R/general/2_get_exon_intron_from_GTF.R

However, I would not recommend using it for regular analysis. It was solely build and used for detecting reads falling in intronic / exonic regions and evaluate the percentage of strand-invasion in intronic/exonic - concordant / discordant orientation (see Fig S16e). 

I generally use the default gencode annotation and currently restrict featureCounts to exonic regions. Strandness depends on the read type (UMI: stranded, any other: unstranded)

PS: We already had several people which tested FLASH-seq with success. I would be interested to hear your feedbacks on it. Please do not hesitate to contact me by email (vincent.hahaut [at] iob.ch) or twitter :-).

Vincent

**Comment by singlecellfan** [comment]
Hi,

Thanks for the quick reply and the code!
Yes, that makes sense. Then I will stick to the regular analysis workflow for now.

I will send you an email once I am done with the analysis. So far from the experimental side everything looked good.

**Comment by vincenthahaut** [comment]
Perfect! Happy to help if you have other questions. 

In general I found that for the regular FLASH-seq, SMART-seq2 pipelines worked well. If you use UMI it gets a bit more complicated.

Good luck with your analysis.
