### ISSUE TITLE
Question on extractin the right UMI - Spacer sequence

### ISSUE THREAD

**Issue by singlecellfan** [vincenthahaut/FLASH-Seq#2]
Hi,
I am trying to run the paired_end_umi script and unfortunately it crashes at this point (2.  get UMI). If I comment it out it runs fine.
What exactly is that code doing?

`      if echo "$ID" | grep -qE "FS_315|315_FS|316_FS|382_FS|317_FS|318_FS"
	then
	echo "TSO_FS_CTAAC"`

Thanks and best regards!

**Comment by vincenthahaut** [comment]
Sorry, the code was intended to reproduce the analysis from the paper, not to be used on a new set. I am planning to create a proper snakemake pipeline that would be compatible with any new dataset but didn't get the chance so far. 

This line simply checks if in the name of the sample ("$ID") there is any of these patterns ("FS_315 OR 315_FS OR ..."). Then it runs the appropriate UMI detection line.

I guess the name of your sample is not fitting that description, hence the crash. If you use the paired-end UMI script, you can safely remove this "if" condition. I left it in case I would like to test several spacers and to avoid running it with the wrong samples.

**Comment by ptranvan** [comment]
Hi @vincenthahaut,

By any chance did you have the time to develop this snakemake pipeline to preprocess raw data ?
